export const COMMON_VOICE_ROOT = '/games/general/voices/tieng-viet'

const path = (folder: string, filename: string) => `${COMMON_VOICE_ROOT}/${folder}/${filename}.mp3`

export const VIETNAMESE_VOICE_MANIFEST = {
  common: {
    chooseMissingLetter: path('common', 'be-hay-chon-chu-con-thieu'),
    chooseMissingOnset: path('common', 'be-hay-chon-phu-am-dau-con-thieu'),
    chooseLetter: path('common', 'be-hay-chon-chu'),
    chooseCorrectAnswer: path('common', 'be-hay-chon-dap-an-dung'),
    chooseSyllable: path('common', 'be-hay-chon-tieng'),
    chooseSyllableWith: path('common', 'be-hay-chon-tieng-co'),
    chooseSyllableWithTone: path('common', 'be-hay-chon-tieng-co'),
    buildSyllable: path('common', 'be-hay-ghep-thanh-tieng'),
    dragMissingLetter: path('common', 'be-hay-keo-chu-vao-cho-trong'),
    listenCarefully: path('common', 'be-hay-nghe-ky-nhe'),
    listenAndChoose: path('common', 'be-hay-nghe-va-chon'),
    findLetterInWord: path('common', 'be-hay-tim-chu-trong-tu'),
    findLetter: path('common', 'be-hay-tim-chu'),
    findSyllable: path('common', 'be-hay-tim-tieng'),
    findWord: path('common', 'be-hay-tim-tu'),
    inSyllable: path('common', 'trong-tieng'),
    inPhrase: path('common', 'trong-cum-tu'),
    inSentence: path('common', 'trong-cau'),
    inLetterRow: path('common', 'trong-day-chu'),
    lowerCaseOf: path('common', 'thuong-cua'),
    upperCaseOf: path('common', 'hoa-cua'),
    matchLetterPrefix: path('common', 'be-hay-ghep-chu'),
    matchLetterSuffix: path('common', 'voi-chu-giong-no'),
    chooseWord: path('common', 'be-hay-chon-tu'),
    chooseWordWith: path('common', 'be-hay-chon-tu-co'),
    choosePhrase: path('common', 'be-hay-chon-cum-tu'),
    choosePhraseWith: path('common', 'be-hay-chon-cum-tu-co'),
    readAndChoose: path('common', 'be-hay-doc-va-chon'),
    beginsWith: path('common', 'bat-dau-bang'),
    connectImageWord: path('common', 'be-hay-noi-moi-hinh-voi-tu-phu-hop'),
    connectOnsetSyllable: path('common', 'tim-tieng-bat-dau-bang-chu-do-roi-noi-lai'),
    hasLetter: path('common', 'co-chu'),
    week3Title: path('common', 'tieng-viet-tuan-3'),
  },
  letters: {
    a: path('letters', 'a'), b: path('letters', 'b'), c: path('letters', 'c'),
    e: path('letters', 'e'), ee: path('letters', 'ee'),
    o: path('letters', 'o'), oo: path('letters', 'oo'), ow: path('letters', 'ow'),
    d: path('letters', 'd'), dd: path('letters', 'dd'),
    i: path('letters', 'i'), k: path('letters', 'k'), h: path('letters', 'h'), l: path('letters', 'l'),
    u: path('letters', 'u'), uw: path('letters', 'uw'), ch: path('letters', 'ch'), kh: path('letters', 'kh'),
    m: path('letters', 'm'), n: path('letters', 'n'), g: path('letters', 'g'), gi: path('letters', 'gi'),
    gh: path('letters', 'gh'), nh: path('letters', 'nh'), ng: path('letters', 'ng'), ngh: path('letters', 'ngh'),
  },
  tones: {
    hỏi: path('tones', 'dau-hoi'), huyền: path('tones', 'dau-huyen'),
    nặng: path('tones', 'dau-nang'), ngã: path('tones', 'dau-nga'), sắc: path('tones', 'dau-sac'),
  },
  syllables: {
    ba: path('syllables', 'ba'), bà: path('syllables', 'ba-huyen'), 'ba ba': path('syllables', 'ba-ba'),
    ca: path('syllables', 'ca'), cà: path('syllables', 'ca-huyen'), cá: path('syllables', 'ca-sac'),
    bè: path('syllables', 'be-huyen'), bé: path('syllables', 'be-sac'), bế: path('syllables', 'be-circumflex-sac'),
    bò: path('syllables', 'bo-huyen'), cò: path('syllables', 'co-huyen'), cỏ: path('syllables', 'co-hoi'),
    bố: path('syllables', 'bo-ocirc-sac'), bộ: path('syllables', 'bo-ocirc-nang'), cô: path('syllables', 'co-ocirc'), cổ: path('syllables', 'co-ocirc-hoi'),
    đa: path('syllables', 'da-dbar'), đá: path('syllables', 'da-dbar-sac'), dê: path('syllables', 'de-dbar-circ'), đỏ: path('syllables', 'do-dbar-hoi'),
    bờ: path('syllables', 'bo-ohorn-huyen'), cờ: path('syllables', 'co-ohorn-huyen'), đỡ: path('syllables', 'do-ohorn-nga'),
    kì: path('syllables', 'ki-huyen'), kẻ: path('syllables', 'ke-hoi'), kẽ: path('syllables', 'ke-nga'), kí: path('syllables', 'ki-sac'),
    bí: path('syllables', 'bi-sac'), đi: path('syllables', 'di-dbar'), ho: path('syllables', 'ho'),
    hồ: path('syllables', 'ho-ocirc-huyen'), hố: path('syllables', 'ho-ocirc-sac'), le: path('syllables', 'le'),
    lá: path('syllables', 'la-sac'), hẹ: path('syllables', 'he-nang'), dù: path('syllables', 'du-huyen'),
    đu: path('syllables', 'du-dbar'), đủ: path('syllables', 'du-dbar-hoi'), dữ: path('syllables', 'du-uhorn-nga'),
    lừ: path('syllables', 'lu-uhorn-huyen'), chú: path('syllables', 'chu-sac'), khỉ: path('syllables', 'khi-hoi'),
    chợ: path('syllables', 'cho-nang'), khô: path('syllables', 'kho-ocirc'), khế: path('syllables', 'khe-circ-sac'),
    chị: path('syllables', 'chi-nang'), kho: path('syllables', 'kho'),
    mẹ: path('syllables', 'me-nang'), me: path('syllables', 'me'), mè: path('syllables', 'me-huyen'),
    nơ: path('syllables', 'no-ohorn'), nô: path('syllables', 'no-ocirc'), mua: path('syllables', 'mua'),
    gà: path('syllables', 'ga-huyen'), gô: path('syllables', 'go-ocirc'), gỗ: path('syllables', 'go-ocirc-nga'),
    giỏ: path('syllables', 'gio-hoi'), giá: path('syllables', 'gia-sac'), già: path('syllables', 'gia-huyen'),
    ghé: path('syllables', 'ghe-sac'), ghe: path('syllables', 'ghe'), ghế: path('syllables', 'ghe-circ-sac'),
    ghẹ: path('syllables', 'ghe-nang'), ghi: path('syllables', 'ghi'), nhà: path('syllables', 'nha-huyen'),
    nhỏ: path('syllables', 'nho-hoi'), nho: path('syllables', 'nho'),
    ngõ: path('syllables', 'ngo-nga'), ngã: path('syllables', 'nga-nga'), ngủ: path('syllables', 'ngu-hoi'),
    nghe: path('syllables', 'nghe'), nghé: path('syllables', 'nghe-sac'), nghỉ: path('syllables', 'nghi-hoi'),
    nghệ: path('syllables', 'nghe-nang'),
  },
  words: {
    ha: path('words', 'ha'), hà: path('words', 'ha'), lan: path('words', 'lan'), nam: path('words', 'nam'),
    'cô bé': path('words', 'co-be'), 'cổ cò': path('words', 'co-co'), 'đá dế': path('words', 'da-de'),
    'đa đa': path('words', 'da-da'), 'ô đỏ': path('words', 'o-do'), 'bờ đê': path('words', 'bo-de'),
    'cá cờ': path('words', 'ca-co'), 'đỡ bé': path('words', 'do-be'), 'cờ đỏ': path('words', 'co-do'), 'đỡ bà': path('words', 'do-ba'),
    'bí đỏ': path('words', 'bi-do'), 'kẻ ô': path('words', 'ke-o'), 'đi đò': path('words', 'di-do'), 'kì đà': path('words', 'ki-da'),
    'lá đỏ': path('words', 'la-do'), 'bờ hồ': path('words', 'bo-ho'), 'cá hố': path('words', 'ca-ho'), 'le le': path('words', 'le-le'),
    'lá hẹ': path('words', 'la-he'), 'đu đủ': path('words', 'du-du'), 'hổ dữ': path('words', 'ho-du'), 'lá khô': path('words', 'la-kho'),
    'chú khỉ': path('words', 'chu-khi'), 'chợ cá': path('words', 'cho-ca'), 'cá kho khế': path('words', 'ca-kho-khe'),
    'chú hề': path('words', 'chu-he'), 'chè ô': path('words', 'che-o'), 'cá dữ': path('words', 'ca-du'),
    'cá mè': path('words', 'ca-me'), 'lá me': path('words', 'la-me'), 'nơ đỏ': path('words', 'no-do'), 'ca nô': path('words', 'ca-no'),
    'gà gô': path('words', 'ga-go'), 'đồ gỗ': path('words', 'do-go'), 'giá đỗ': path('words', 'gia-do'), 'cụ già': path('words', 'cu-gia'),
    'ghế đá': path('words', 'ghe-da'), 'ghẹ đỏ': path('words', 'ghe-do'), 'nhà gỗ': path('words', 'nha-go'), 'lá nho': path('words', 'la-nho'),
    'ngã ba': path('words', 'nga-ba'), 'ngõ nhỏ': path('words', 'ngo-nho'), 'củ nghệ': path('words', 'cu-nghe'), 'nghỉ hè': path('words', 'nghi-he'),
    'hũ cá': path('words', 'hu-ca'), 'nhà ga': path('words', 'nha-ga'), 'ngủ mơ': path('words', 'ngu-mo'), 'bờ ngõ': path('words', 'bo-ngo'),
    'nho nhỏ': path('words', 'nho-nho'), 'ghế gỗ': path('words', 'ghe-go'),
  },
  sentences: {
    'Ba và bé': path('sentences', 'ba-va-be'),
    'Bê có cỏ.': path('sentences', 'be-co-co'),
    'Bố bế bể cá.': path('sentences', 'bo-be-be-ca'),
    'Bé có ô đỏ.': path('sentences', 'be-co-o-do'),
    'Bố đỡ bé.': path('sentences', 'bo-do-be'),
    'Bờ đê có dê.': path('sentences', 'bo-de-co-de'),
    'Bà có ô đỏ.': path('sentences', 'ba-co-o-do'),
    'Nam vẽ kì đà.': path('sentences', 'nam-ve-ki-da'), 'Kì đà bò ở kẽ đá.': path('sentences', 'ki-da-bo-o-ke-da'),
    'Le le bơi trên hồ.': path('sentences', 'le-le-boi-tren-ho'), 'Bé bị ho.': path('sentences', 'be-bi-ho'),
    'Bà đã có lá hẹ.': path('sentences', 'ba-da-co-la-he'), 'Đu đủ chín ngọt lừ.': path('sentences', 'du-du-chin-ngot-lu'),
    'Cá hố là cá dữ.': path('sentences', 'ca-ho-la-ca-du'), 'Mấy chú khỉ ăn chuối.': path('sentences', 'may-chu-khi-an-chuoi'),
    'Chị có cá kho khế.': path('sentences', 'chi-co-ca-kho-khe'), 'Chị cho bé cá cờ.': path('sentences', 'chi-cho-be-ca-co'),
    'Dì Kha cho Hà đi chợ.': path('sentences', 'di-kha-cho-ha-di-cho'),
    'Mẹ mua nơ cho Hà.': path('sentences', 'me-mua-no-cho-ha'),
    'Bố mẹ cho Hà đi ca nô.': path('sentences', 'bo-me-cho-ha-di-ca-no'),
    'Hà có giỏ trứng gà.': path('sentences', 'ha-co-gio-trung-ga'),
    'Bà che gió cho ba chú gà.': path('sentences', 'ba-che-gio-cho-ba-chu-ga'),
    'Hà ghé nhà bà.': path('sentences', 'ha-ghe-nha-ba'),
    'Nhà bà ở ngõ nhỏ.': path('sentences', 'nha-ba-o-ngo-nho'),
    'Mẹ nhờ Hà bê ghế nhỏ.': path('sentences', 'me-nho-ha-be-ghe-nho'),
    'Nghé theo mẹ ra ngõ.': path('sentences', 'nghe-theo-me-ra-ngo'),
    'Nghé đã no cỏ.': path('sentences', 'nghe-da-no-co'),
    'Nghé ngủ ở bờ đê.': path('sentences', 'nghe-ngu-o-bo-de'),
    'Mẹ ghé nhà bà.': path('sentences', 'me-ghe-nha-ba'),
  },
} as const

/** New Week 4 target recordings. The files are recorded separately and never synthesized at runtime. */
export const TIENG_VIET_1_WEEK_4_REQUIRED_VOICE_PATHS = [
  VIETNAMESE_VOICE_MANIFEST.letters.m, VIETNAMESE_VOICE_MANIFEST.letters.n,
  VIETNAMESE_VOICE_MANIFEST.letters.g, VIETNAMESE_VOICE_MANIFEST.letters.gi,
  VIETNAMESE_VOICE_MANIFEST.letters.gh, VIETNAMESE_VOICE_MANIFEST.letters.nh,
  VIETNAMESE_VOICE_MANIFEST.letters.ng, VIETNAMESE_VOICE_MANIFEST.letters.ngh,
  VIETNAMESE_VOICE_MANIFEST.syllables.mẹ, VIETNAMESE_VOICE_MANIFEST.syllables.me,
  VIETNAMESE_VOICE_MANIFEST.syllables.mè, VIETNAMESE_VOICE_MANIFEST.syllables.nơ,
  VIETNAMESE_VOICE_MANIFEST.syllables.nô, VIETNAMESE_VOICE_MANIFEST.syllables.mua,
  VIETNAMESE_VOICE_MANIFEST.syllables.gà, VIETNAMESE_VOICE_MANIFEST.syllables.gô,
  VIETNAMESE_VOICE_MANIFEST.syllables.gỗ, VIETNAMESE_VOICE_MANIFEST.syllables.giỏ,
  VIETNAMESE_VOICE_MANIFEST.syllables.giá, VIETNAMESE_VOICE_MANIFEST.syllables.già,
  VIETNAMESE_VOICE_MANIFEST.syllables.ghé, VIETNAMESE_VOICE_MANIFEST.syllables.ghe,
  VIETNAMESE_VOICE_MANIFEST.syllables.ghế, VIETNAMESE_VOICE_MANIFEST.syllables.ghẹ,
  VIETNAMESE_VOICE_MANIFEST.syllables.ghi, VIETNAMESE_VOICE_MANIFEST.syllables.nhà,
  VIETNAMESE_VOICE_MANIFEST.syllables.nhỏ, VIETNAMESE_VOICE_MANIFEST.syllables.nho,
  VIETNAMESE_VOICE_MANIFEST.syllables.ngõ, VIETNAMESE_VOICE_MANIFEST.syllables.ngã,
  VIETNAMESE_VOICE_MANIFEST.syllables.ngủ, VIETNAMESE_VOICE_MANIFEST.syllables.nghe,
  VIETNAMESE_VOICE_MANIFEST.syllables.nghé, VIETNAMESE_VOICE_MANIFEST.syllables.nghỉ,
  VIETNAMESE_VOICE_MANIFEST.syllables.nghệ,
  VIETNAMESE_VOICE_MANIFEST.words['cá mè'], VIETNAMESE_VOICE_MANIFEST.words['lá me'],
  VIETNAMESE_VOICE_MANIFEST.words['nơ đỏ'], VIETNAMESE_VOICE_MANIFEST.words['ca nô'],
  VIETNAMESE_VOICE_MANIFEST.words['gà gô'], VIETNAMESE_VOICE_MANIFEST.words['đồ gỗ'],
  VIETNAMESE_VOICE_MANIFEST.words['giá đỗ'], VIETNAMESE_VOICE_MANIFEST.words['cụ già'],
  VIETNAMESE_VOICE_MANIFEST.words['ghế đá'], VIETNAMESE_VOICE_MANIFEST.words['ghẹ đỏ'],
  VIETNAMESE_VOICE_MANIFEST.words['nhà gỗ'], VIETNAMESE_VOICE_MANIFEST.words['lá nho'],
  VIETNAMESE_VOICE_MANIFEST.words['ngã ba'], VIETNAMESE_VOICE_MANIFEST.words['ngõ nhỏ'],
  VIETNAMESE_VOICE_MANIFEST.words['củ nghệ'], VIETNAMESE_VOICE_MANIFEST.words['nghỉ hè'],
  VIETNAMESE_VOICE_MANIFEST.words['hũ cá'], VIETNAMESE_VOICE_MANIFEST.words['nhà ga'],
  VIETNAMESE_VOICE_MANIFEST.words['ngủ mơ'], VIETNAMESE_VOICE_MANIFEST.words['bờ ngõ'],
  VIETNAMESE_VOICE_MANIFEST.words['nho nhỏ'], VIETNAMESE_VOICE_MANIFEST.words['ghế gỗ'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Mẹ mua nơ cho Hà.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Bố mẹ cho Hà đi ca nô.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Hà có giỏ trứng gà.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Bà che gió cho ba chú gà.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Hà ghé nhà bà.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Nhà bà ở ngõ nhỏ.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Mẹ nhờ Hà bê ghế nhỏ.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Nghé theo mẹ ra ngõ.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Nghé đã no cỏ.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Nghé ngủ ở bờ đê.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Mẹ ghé nhà bà.'],
] as const

/** Files requested for Week 3; paths are mapped before recording and are never inferred from text. */
export const TIENG_VIET_1_WEEK_3_REQUIRED_VOICE_PATHS = [
  VIETNAMESE_VOICE_MANIFEST.common.chooseWord, VIETNAMESE_VOICE_MANIFEST.common.chooseWordWith,
  VIETNAMESE_VOICE_MANIFEST.common.choosePhrase, VIETNAMESE_VOICE_MANIFEST.common.choosePhraseWith,
  VIETNAMESE_VOICE_MANIFEST.common.readAndChoose, VIETNAMESE_VOICE_MANIFEST.common.beginsWith,
  VIETNAMESE_VOICE_MANIFEST.common.hasLetter,
  VIETNAMESE_VOICE_MANIFEST.letters.i, VIETNAMESE_VOICE_MANIFEST.letters.k,
  VIETNAMESE_VOICE_MANIFEST.letters.h, VIETNAMESE_VOICE_MANIFEST.letters.l,
  VIETNAMESE_VOICE_MANIFEST.letters.u, VIETNAMESE_VOICE_MANIFEST.letters.uw,
  VIETNAMESE_VOICE_MANIFEST.letters.ch, VIETNAMESE_VOICE_MANIFEST.letters.kh,
  VIETNAMESE_VOICE_MANIFEST.syllables.kì, VIETNAMESE_VOICE_MANIFEST.syllables.kẻ,
  VIETNAMESE_VOICE_MANIFEST.syllables.kẽ, VIETNAMESE_VOICE_MANIFEST.syllables.kí,
  VIETNAMESE_VOICE_MANIFEST.syllables.bí, VIETNAMESE_VOICE_MANIFEST.syllables.đi,
  VIETNAMESE_VOICE_MANIFEST.syllables.ho, VIETNAMESE_VOICE_MANIFEST.syllables.hồ,
  VIETNAMESE_VOICE_MANIFEST.syllables.hố, VIETNAMESE_VOICE_MANIFEST.syllables.le,
  VIETNAMESE_VOICE_MANIFEST.syllables.lá, VIETNAMESE_VOICE_MANIFEST.syllables.hẹ,
  VIETNAMESE_VOICE_MANIFEST.syllables.dù, VIETNAMESE_VOICE_MANIFEST.syllables.đu,
  VIETNAMESE_VOICE_MANIFEST.syllables.đủ, VIETNAMESE_VOICE_MANIFEST.syllables.dữ,
  VIETNAMESE_VOICE_MANIFEST.syllables.lừ, VIETNAMESE_VOICE_MANIFEST.syllables.chú,
  VIETNAMESE_VOICE_MANIFEST.syllables.khỉ, VIETNAMESE_VOICE_MANIFEST.syllables.chợ,
  VIETNAMESE_VOICE_MANIFEST.syllables.khô, VIETNAMESE_VOICE_MANIFEST.syllables.khế,
  VIETNAMESE_VOICE_MANIFEST.syllables.chị, VIETNAMESE_VOICE_MANIFEST.syllables.kho,
  VIETNAMESE_VOICE_MANIFEST.words['bí đỏ'], VIETNAMESE_VOICE_MANIFEST.words['kẻ ô'],
  VIETNAMESE_VOICE_MANIFEST.words['đi đò'], VIETNAMESE_VOICE_MANIFEST.words['kì đà'],
  VIETNAMESE_VOICE_MANIFEST.words['lá đỏ'], VIETNAMESE_VOICE_MANIFEST.words['bờ hồ'],
  VIETNAMESE_VOICE_MANIFEST.words['cá hố'], VIETNAMESE_VOICE_MANIFEST.words['le le'],
  VIETNAMESE_VOICE_MANIFEST.words['lá hẹ'], VIETNAMESE_VOICE_MANIFEST.words['đu đủ'],
  VIETNAMESE_VOICE_MANIFEST.words['hổ dữ'], VIETNAMESE_VOICE_MANIFEST.words['lá khô'],
  VIETNAMESE_VOICE_MANIFEST.words['chú khỉ'], VIETNAMESE_VOICE_MANIFEST.words['chợ cá'],
  VIETNAMESE_VOICE_MANIFEST.words['cá kho khế'], VIETNAMESE_VOICE_MANIFEST.words['chú hề'],
  VIETNAMESE_VOICE_MANIFEST.words['chè ô'], VIETNAMESE_VOICE_MANIFEST.words['cá dữ'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Nam vẽ kì đà.'], VIETNAMESE_VOICE_MANIFEST.sentences['Kì đà bò ở kẽ đá.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Le le bơi trên hồ.'], VIETNAMESE_VOICE_MANIFEST.sentences['Bé bị ho.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Bà đã có lá hẹ.'], VIETNAMESE_VOICE_MANIFEST.sentences['Đu đủ chín ngọt lừ.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Cá hố là cá dữ.'], VIETNAMESE_VOICE_MANIFEST.sentences['Mấy chú khỉ ăn chuối.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Chị có cá kho khế.'], VIETNAMESE_VOICE_MANIFEST.sentences['Chị cho bé cá cờ.'],
  VIETNAMESE_VOICE_MANIFEST.sentences['Dì Kha cho Hà đi chợ.'],
] as const

const instructionNames = {
  FIND_LETTER: 'findLetter', CHOOSE_LETTER: 'chooseLetter', LISTEN_AND_CHOOSE: 'listenAndChoose',
  FIND_SYLLABLE: 'findSyllable', CHOOSE_SYLLABLE: 'chooseSyllable',
  CHOOSE_SYLLABLE_WITH_TONE: 'chooseSyllableWithTone', FIND_WORD: 'findWord',
  FIND_LETTER_IN_WORD: 'findLetterInWord', FILL_LETTER: 'dragMissingLetter', FILL_MISSING_LETTER: 'chooseMissingLetter',
  FILL_ONSET: 'chooseMissingOnset', CONNECT_IMAGE_WORD: 'connectImageWord', CONNECT_ONSET_SYLLABLE: 'connectOnsetSyllable',
  CHOOSE_SYLLABLE_WITH: 'chooseSyllableWith',
  BUILD_SYLLABLE: 'buildSyllable', CHOOSE_ANSWER: 'chooseCorrectAnswer',
  CHOOSE_WORD: 'chooseWord', CHOOSE_WORD_WITH: 'chooseWordWith',
  CHOOSE_PHRASE: 'choosePhrase', CHOOSE_PHRASE_WITH: 'choosePhraseWith',
  READ_AND_CHOOSE: 'readAndChoose', BEGINS_WITH: 'beginsWith', HAS_LETTER: 'hasLetter',
} as const

export type VietnameseInstructionKey = keyof typeof instructionNames
export type VietnameseVoiceTargetType = keyof Pick<typeof VIETNAMESE_VOICE_MANIFEST, 'letters' | 'tones' | 'syllables' | 'words' | 'sentences'>

export function getVietnameseInstructionVoice(instruction: string): string | undefined {
  const key = instructionNames[instruction as VietnameseInstructionKey]
  return key ? VIETNAMESE_VOICE_MANIFEST.common[key] : undefined
}

const explicitTargetPaths: Record<VietnameseVoiceTargetType, Readonly<Record<string, string>>> = {
  letters: {
    a: VIETNAMESE_VOICE_MANIFEST.letters.a, b: VIETNAMESE_VOICE_MANIFEST.letters.b,
    c: VIETNAMESE_VOICE_MANIFEST.letters.c, e: VIETNAMESE_VOICE_MANIFEST.letters.e,
    ê: VIETNAMESE_VOICE_MANIFEST.letters.ee, o: VIETNAMESE_VOICE_MANIFEST.letters.o,
    ô: VIETNAMESE_VOICE_MANIFEST.letters.oo, ơ: VIETNAMESE_VOICE_MANIFEST.letters.ow,
    d: VIETNAMESE_VOICE_MANIFEST.letters.d, đ: VIETNAMESE_VOICE_MANIFEST.letters.dd,
    i: VIETNAMESE_VOICE_MANIFEST.letters.i, k: VIETNAMESE_VOICE_MANIFEST.letters.k,
    h: VIETNAMESE_VOICE_MANIFEST.letters.h, l: VIETNAMESE_VOICE_MANIFEST.letters.l,
    u: VIETNAMESE_VOICE_MANIFEST.letters.u, ư: VIETNAMESE_VOICE_MANIFEST.letters.uw,
    ch: VIETNAMESE_VOICE_MANIFEST.letters.ch, kh: VIETNAMESE_VOICE_MANIFEST.letters.kh,
    m: VIETNAMESE_VOICE_MANIFEST.letters.m, n: VIETNAMESE_VOICE_MANIFEST.letters.n,
    g: VIETNAMESE_VOICE_MANIFEST.letters.g, gi: VIETNAMESE_VOICE_MANIFEST.letters.gi,
    gh: VIETNAMESE_VOICE_MANIFEST.letters.gh, nh: VIETNAMESE_VOICE_MANIFEST.letters.nh,
    ng: VIETNAMESE_VOICE_MANIFEST.letters.ng, ngh: VIETNAMESE_VOICE_MANIFEST.letters.ngh,
  },
  tones: {
    'dấu hỏi': VIETNAMESE_VOICE_MANIFEST.tones.hỏi, 'dấu huyền': VIETNAMESE_VOICE_MANIFEST.tones.huyền,
    'dấu nặng': VIETNAMESE_VOICE_MANIFEST.tones.nặng, 'dấu ngã': VIETNAMESE_VOICE_MANIFEST.tones.ngã,
    'dấu sắc': VIETNAMESE_VOICE_MANIFEST.tones.sắc,
  },
  syllables: VIETNAMESE_VOICE_MANIFEST.syllables,
  words: VIETNAMESE_VOICE_MANIFEST.words,
  sentences: VIETNAMESE_VOICE_MANIFEST.sentences,
}

/** Explicit text-to-file mapping: never derive a filename from Vietnamese Unicode. */
export function resolveVietnameseTargetVoice(type: VietnameseVoiceTargetType, target: string): string | undefined {
  const normalized = target.normalize('NFC')
  const paths = explicitTargetPaths[type]
  const lower = normalized.toLocaleLowerCase('vi-VN')
  if (paths[normalized]) return paths[normalized]
  if (paths[lower]) return paths[lower]
  const equivalent = Object.keys(paths).find(key => key.normalize('NFC').toLocaleLowerCase('vi-VN') === lower)
  return equivalent ? paths[equivalent] : undefined
}
