'use client'
import Link from 'next/link'
import { useState } from 'react'
import { Plus, Search, Download } from 'lucide-react'
import { Entity, Row, modules, labels, displayName, formatVND, formatDate, normalize, dateKey, parseMoney } from '../_lib/model'
import { api, useDemo } from './Provider'
import EntityForm from './EntityForm'

export function RecordTable({ entity, rows, actions = true }: { entity: Entity; rows: Row[]; actions?: boolean }) {
  const { data, refresh, notify } = useDemo(); const [editing, setEditing] = useState<Partial<Row> | null>(null); const [detail, setDetail] = useState<Row | null>(null); const [busy, setBusy] = useState(false)
  const run = async (r: Row, operation: 'delete' | 'pay' | 'save') => {
    let amount: number | undefined
    if (operation === 'pay') { const v = prompt(`Số tiền thanh toán (còn ${formatVND(r.remainingAmount)}):`); if (!v) return; amount = parseMoney(v) }
    if (!confirm(operation === 'delete' ? 'Xóa bản ghi này và các giao dịch được tạo từ chứng từ này?' : operation === 'pay' ? `Xác nhận thanh toán ${formatVND(amount)}?` : 'Xác nhận hoàn thành công việc?')) return
    setBusy(true); try { await api({ entity, id: r.id, operation, amount, data: operation === 'save' ? { ...r, status: 'completed' } : undefined, requestId: crypto.randomUUID() }); await refresh(); notify('Cập nhật thành công') } catch (e) { notify(e instanceof Error ? e.message : 'Thao tác thất bại') } finally { setBusy(false) }
  }
  const fields = modules[entity].fields.filter(f => !['note', 'attachmentUrl', 'address', 'taxCode', 'remindAt', 'expectedEndDate', 'endDate', 'seedCost', 'seedQuantity', 'transactionId'].includes(f.key)).slice(0, entity === 'harvests' ? 10 : 7)
  const cell = (r: Row, key: string) => { const f = modules[entity].fields.find(f => f.key === key); const v = r[key]; return f?.ref ? displayName(data[f.ref].find(x => x.id === v)) : f?.kind === 'money' ? formatVND(v) : f?.kind === 'date' || f?.kind === 'datetime-local' ? formatDate(v) : labels[String(v)] || String(v ?? '—') }
  return <>{!rows.length ? <div className="demo-empty">Chưa có dữ liệu phù hợp.</div> : <div className="demo-table-wrap"><table><thead><tr>{fields.map(f => <th key={f.key}>{f.label}</th>)}{['receivables', 'payables'].includes(entity) && <><th>Đã trả</th><th>Còn lại</th></>}{actions && <th>Thao tác</th>}</tr></thead><tbody>{rows.map(r => <tr key={r.id}>{fields.map(f => <td key={f.key}>{f.key === 'status' || f.key === 'paymentStatus' ? <span className={`demo-badge ${r[f.key] === 'completed' || r[f.key] === 'paid' ? 'success' : ''}`}>{cell(r, f.key)}</span> : cell(r, f.key)}{f.key === 'dueAt' && !['completed', 'cancelled', 'paid'].includes(String(r.status)) && String(r.dueAt) < new Date().toISOString() && <span className="demo-overdue">Quá hạn</span>}</td>)}{['receivables', 'payables'].includes(entity) && <><td>{formatVND(r.paidAmount)}</td><td>{formatVND(r.remainingAmount)}</td></>}{actions && <td><div className="demo-row-actions"><button onClick={() => setDetail(r)}>Chi tiết</button><button disabled={busy} onClick={() => setEditing(r)}>Sửa</button>{entity === 'transactions' && <button onClick={() => { const { id, ...rest } = r; setEditing(rest) }}>Nhân bản</button>}{entity === 'tasks' && r.status !== 'completed' && <button disabled={busy} onClick={() => run(r, 'save')}>Hoàn thành</button>}{['receivables', 'payables'].includes(entity) && Number(r.remainingAmount) > 0 && <button disabled={busy} onClick={() => run(r, 'pay')}>Thanh toán</button>}<button disabled={busy} className="demo-danger-text" onClick={() => run(r, 'delete')}>Xóa</button></div></td>}</tr>)}</tbody></table></div>}{editing && <EntityForm entity={entity} initial={editing} onClose={() => setEditing(null)} />}{detail && <div className="demo-modal-backdrop"><section className="demo-modal" role="dialog" aria-modal="true" aria-label="Chi tiết"><h2>{displayName(detail)}</h2><dl className="demo-details">{modules[entity].fields.map(f => <div key={f.key}><dt>{f.label}</dt><dd>{cell(detail, f.key)}</dd></div>)}</dl>{['partners', 'crops', 'ponds'].includes(entity) && <Link className="demo-primary" href={`/chatbot/demo/${entity}/${detail.id}`}>Xem hoạt động liên quan</Link>}<h3>Lịch sử thay đổi</h3>{data.auditLogs.filter(a => a.entityType === entity && a.entityId === detail.id).map(a => <p key={a.id}>{formatDate(a.createdAt)} · {a.action} · {a.source}</p>)}<button onClick={() => setDetail(null)}>Đóng</button></section></div>}</>
}
export default function Records({ entity }: { entity: Entity }) {
  const { data, loading } = useDemo(); const [creating, setCreating] = useState(false); const [search, setSearch] = useState(''); const [filters, setFilters] = useState<Record<string, string>>({})
  const dateField = modules[entity].fields.find(f => f.kind === 'date' || f.kind === 'datetime-local')?.key
  const rows = data[entity].filter(r => (!search || normalize(Object.values(r).join(' ')).includes(normalize(search)) || modules[entity].fields.some(f => f.ref && normalize(displayName(data[f.ref].find(x => x.id === r[f.key]))).includes(normalize(search)))) && Object.entries(filters).every(([key, value]) => !value || key === 'from' ? !value || !dateField || dateKey(r[dateField]) >= value : key === 'to' ? !dateField || dateKey(r[dateField]) <= value : String(r[key]) === value))
  return <><div className="demo-page-heading"><div><small>QUẢN LÝ HOẠT ĐỘNG</small><h1>{modules[entity].title}</h1><p>{rows.length} bản ghi · Quản lý tập trung, cập nhật dễ dàng</p></div><div className="demo-inline"><a className="demo-button" href={`/chatbot/demo/api/export?entity=${entity}&from=${filters.from || ''}&to=${filters.to || ''}`}><Download size={16} />Xuất Excel</a><button className="demo-primary" onClick={() => setCreating(true)}><Plus size={18} />Thêm mới</button></div></div><section className="demo-panel"><div className="demo-filters"><label className="demo-search"><Search size={17} /><input placeholder="Tìm kiếm…" aria-label="Tìm kiếm" value={search} onChange={e => setSearch(e.target.value)} /></label>{dateField && <><label>Từ ngày<input type="date" value={filters.from || ''} onChange={e => setFilters({ ...filters, from: e.target.value })} /></label><label>Đến ngày<input type="date" value={filters.to || ''} onChange={e => setFilters({ ...filters, to: e.target.value })} /></label></>}{modules[entity].fields.filter(f => f.options || f.ref).map(f => <select aria-label={f.label} key={f.key} value={filters[f.key] || ''} onChange={e => setFilters({ ...filters, [f.key]: e.target.value })}><option value="">Tất cả {f.label.toLowerCase()}</option>{f.options ? f.options.map(o => <option key={o} value={o}>{labels[o] || o}</option>) : data[f.ref!].map(r => <option key={r.id} value={r.id}>{displayName(r)}</option>)}</select>)}<button onClick={() => { setFilters({}); setSearch('') }}>Xóa bộ lọc</button></div>{loading ? <div className="demo-empty">Đang tải dữ liệu…</div> : <RecordTable entity={entity} rows={rows} />}</section>{creating && <EntityForm entity={entity} onClose={() => setCreating(false)} />}</>
}
