import { Dataset, Row, dateKey, today, displayName } from '../_lib/model'
export const sum = (rows: Row[], key: string) => rows.reduce((n, r) => n + Number(r[key] || 0), 0)
export function finance(rows: Row[]) { const income = sum(rows.filter(r => r.type === 'income'), 'amount'); const expense = sum(rows.filter(r => r.type === 'expense'), 'amount'); return { income, expense, cashflow: income - expense } }
export const getTodayFinanceSummary = (d: Dataset) => finance(d.transactions.filter(r => dateKey(r.transactionDate) === today()))
export const getMonthlyFinanceSummary = (d: Dataset) => finance(d.transactions.filter(r => dateKey(r.transactionDate).slice(0, 7) === today().slice(0, 7)))
export const getDebtSummary = (d: Dataset) => ({ receivables: sum(d.receivables, 'remainingAmount'), payables: sum(d.payables, 'remainingAmount') })
export function getTaskSummary(d: Dataset) { const open = d.tasks.filter(r => !['completed', 'cancelled'].includes(String(r.status))); return { today: open.filter(r => dateKey(r.dueAt) === today()).length, overdue: open.filter(r => String(r.dueAt) < new Date().toISOString()).length, upcoming: open.filter(r => String(r.dueAt) > new Date().toISOString() && String(r.dueAt) < new Date(Date.now() + 7 * 86400000).toISOString()).length, completed: d.tasks.filter(r => r.status === 'completed').length } }
export const getActiveCropSummary = (d: Dataset) => d.crops.filter(r => ['active', 'harvesting'].includes(String(r.status)))
export const getHarvestSummary = (d: Dataset) => ({ quantity: sum(d.harvests, 'quantityKg'), revenue: sum(d.harvests, 'totalAmount'), expense: sum(d.cropExpenses, 'amount'), profit: sum(d.harvests, 'totalAmount') - sum(d.cropExpenses, 'amount') })
function profitability(d: Dataset, list: Row[], key: string) { return list.map(r => { const revenue = sum(d.harvests.filter(h => h[key] === r.id), 'totalAmount'); const expense = sum(d.cropExpenses.filter(h => h[key] === r.id), 'amount'); return { id: r.id, name: displayName(r), revenue, expense, profit: revenue - expense } }) }
export const getCropProfitability = (d: Dataset) => profitability(d, d.crops, 'cropId')
export const getPondProfitability = (d: Dataset) => profitability(d, d.ponds, 'pondId')
export const getExpenseByCategory = (d: Dataset) => d.categories.filter(c => c.type === 'expense').map(c => ({ name: displayName(c), expense: sum(d.cropExpenses.filter(e => e.categoryId === c.id), 'amount') }))
export function dashboard(d: Dataset) { return { today: getTodayFinanceSummary(d), month: getMonthlyFinanceSummary(d), debts: getDebtSummary(d), tasks: getTaskSummary(d), harvest: getHarvestSummary(d), crops: getCropProfitability(d), ponds: getPondProfitability(d), categories: getExpenseByCategory(d), active: getActiveCropSummary(d), monthly: Array.from({ length: 12 }, (_, i) => { const month = `${today().slice(0, 4)}-${String(i + 1).padStart(2, '0')}`; return { name: `T${i + 1}`, ...finance(d.transactions.filter(t => dateKey(t.transactionDate).slice(0, 7) === month)) } }), topDebts: d.partners.map(p => ({ name: displayName(p), remaining: sum([...d.receivables, ...d.payables].filter(r => r.partnerId === p.id), 'remainingAmount') })).sort((a, b) => b.remaining - a.remaining).slice(0, 5) } }
